import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function StaticLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div>
        ---Static Layout--- <Link href="/">go Home</Link>
      </div>

      <main className="mx-2">{children}</main>
    </>
  );
}
