import type { Metadata } from "next";
import Header from "./Header";
import ProvidersWrapper from "@/app/providers";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/next-auth/authOptions";
import ModalManager from "../modals/ModalManager";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function SiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const serverSession = null;
  const serverSession = await getServerSession(authOptions);
  // console.log("---Site Layout::::", JSON.stringify(serverSession, null, 2));

  return (
    <>
      <ProvidersWrapper serverSession={serverSession}>
        <ModalManager />
        <Header session={serverSession} />
        <main className="mx-2">{children}</main>
      </ProvidersWrapper>
    </>
  );
}
